Обновление текста на русском и английском
shikimori/shikimori pull request #2769
Opened 2024-01-14 18:50 UTC by Blueberryy

**Русская версия**
 - Исправлены некоторые опечатки.
 - Теперь многие сообщения обращаются к пользователю на вы.
 - Полностью заменено слово "аккаунт" на "учётная запись".
 - Полностью заменено слово "бан" на "блокировка".
 - Полностью заменено слово "тег" на "метка".

 **Английская версия**
 - Заменено слово "Ranobe" на "Light novel".
 - Добавлен перевод жанров достижений.

2024-01-27 16:18 UTC, morr requested changes
Изменений много, лучше было бы их заранее согласовать, чтобы не делать лишнюю работу. Отписал в комментариях, с чем не согласен.

2024-01-27 16:18 UTC, morr commented on config/locales/ru.yml
> +        invalid_transition: не удалось перейти
технический термин. перевод ошибочен. ошибка означает "невозможно перевести из текущего статуса в какой-то другой статус, потому что переход из текущего статуса в другой статус не разрешено в коде". но это слишком длинно и непонятно, лучше оставить английский вариант.

2024-01-27 16:18 UTC, morr commented on config/locales/ru.yml
> +        invalid_transition: не удалось перейти
выше описал

2024-01-27 16:18 UTC, morr commented on config/locales/ru.yml
> +          (для случаев с длинным названием, когда анализатор самостоятельно не может найти эпизоды)
анализатор означает другое. тут именно парсер, у этого слова нет прямого синонима в русском языке.

2024-01-27 16:18 UTC, morr commented on config/locales/ru.yml
> +        tv: TV-сериал
оставить как было

2024-01-27 16:18 UTC, morr commented on config/locales/ru.yml
> +        tv_special: TV-спецвыпуск
оставить как было

2024-01-27 16:18 UTC, morr commented on config/locales/ru.yml
> +          tv_special: TV-спешл
оставить как было

2024-01-27 16:18 UTC, morr commented on config/locales/ru.yml
> +        copyrighted: заблокирован за автор. право
без разницы, это остатки от онлайн просмотра, на сайте нигде не отображается

2024-01-27 16:18 UTC, morr commented on config/locales/ru.yml
> +        limited: Ограничена (350 пикс.)
оставить как было

2024-01-27 16:18 UTC, morr commented on config/locales/view_objects.ru.yml
> +          tv_special: Аниме TV-спецвыпуски
оставить как было

2024-01-27 16:18 UTC, morr commented on config/locales/views/application.ru.yml
> +        profile: Учётная запись
Оставить `Аккаунт` тут и во всех остальных местах

2024-01-27 16:18 UTC, morr commented on config/locales/views/devise.en.yml
> +      sign_up: Create new account
Все это уже ни на что не влияет. Английская локализация доступна только зарегистрированным пользователям.

2024-01-27 16:18 UTC, morr commented on config/locales/views/pages.ru.yml
> +        Перед ником пользователя пишется «@».
На клавиатуре нет этих кавычек, и я не буду их искать в гугле каждый раз, когда мне нужно будет что-то взять в кавычки в тексте. Поэтому и не нужно начинать их применять в файлах локализации.

2024-02-03 08:34 UTC, x9136 commented on config/locales/ru.yml
> +        invalid_transition: не удалось перейти
> "невозможно перевести из текущего статуса в какой-то другой статус, потому что переход из текущего статуса в другой статус не разрешено в коде"

Это звучит как «Смена статуса запрещена в коде», но я бы тоже не менял, потому что практическая польза важнее.

2024-02-03 08:45 UTC, x9136 commented on config/locales/views/pages.ru.yml
> +        Перед ником пользователя пишется «@».
Хотя по правилам русского языка используются кавычки-ёлочки, для них, увы, нужно ставить отдельную раскладку, типа раскладки Бирмана. Она не нарушает обычную раскладку, но ставить её есть смысл, когда много работаешь с текстом или часто напрягает, что для правильности нужно делать кучу действий.

2024-02-03 08:56 UTC, x9136 commented
> Заменено слово "Ranobe" на "Light novel"

А зачем? Я бы наоборот сделал везде Ranobe — оно короче и меньше путает. Имея в типах Novel и Light novel не сразу понятно в чём разница вообще — в объёме, в сложности, в жестокости или это формальное различие, а при Novel и Ranobe сразу понятно, что это другое.

2024-04-04 11:26 UTC, Blueberryy commented
> > Заменено слово "Ranobe" на "Light novel"
> 
> А зачем? Я бы наоборот сделал везде Ranobe — оно короче и меньше путает. Имея в типах Novel и Light novel не сразу понятно в чём разница вообще — в объёме, в сложности, в жестокости или это формальное различие, а при Novel и Ranobe сразу понятно, что это другое.

Да там просто везде было Light Novel, а в некоторых местах Ranobe. Для согласованности текста.

2024-04-26 17:09 UTC, merged

2024-04-26 18:31 UTC, morr commented
@Blueberryy спасибо! Все выложил на сайте. Кое-что дополнительно подправив